D=[("apple","apel","/aepl/","I eat apple","Saya makan apel","Noun","A1"),
("water","air","/wot.r/","Drink water","Minum air","Noun","A1"),
("book","buku","/buk/","Read book","Baca buku","Noun","A1"),
("food","makanan","/fud/","Good food","Makanan enak","Noun","A1"),
("eat","makan","/it/","We eat","Kami makan","Verb","A1"),
("drink","minum","/drnk/","Drink juice","Minum jus","Verb","A1"),
("read","baca","/rid/","Read text","Baca teks","Verb","A1"),
("write","tulis","/rit/","Write now","Tulis sekarang","Verb","A1"),
("run","lari","/rn/","Run fast","Lari cepat","Verb","A1"),
("walk","jalan","/wok/","Walk slow","Jalan pelan","Verb","A1"),
("happy","bahagia","/hepi/","Look happy","Lihat bahagia","Adj","A1"),
("sad","sedih","/sad/","Feel sad","Rasa sedih","Adj","A1"),
("big","besar","/bg/","Big car","Mobil besar","Adj","A1"),
("small","kecil","/smol/","Small dog","Anjing kecil","Adj","A1"),
("good","baik","/gd/","Good job","Kerja bagus","Adj","A1"),
("bad","buruk","/bad/","Bad day","Hari buruk","Adj","A1"),
("new","baru","/nu/","New phone","HP baru","Adj","A1"),
("old","tua","/old/","Old man","Pria tua","Adj","A1"),
("hot","panas","/ht/","Very hot","Sangat panas","Adj","A1"),
("cold","dingin","/old/","Cold water","Air dingin","Adj","A1")]
+ [("family","keluarga","/fam.li/","My family","Keluargaku","Noun","A1"),
("friend","teman","/frend/","Best friend","Sahabat","Noun","A1"),
("house","rumah","/haus/","Big house","Rumah besar","Noun","A1"),
("school","sekolah","/skul/","Go school","Ke sekolah","Noun","A1"),
("car","mobil","/kar/","Fast car","Mobil kencang","Noun","A1"),
("dog","anjing","/dog/","Cute dog","Anjing lucu","Noun","A1"),
("cat","kucing","/kat/","Wild cat","Kucing liar","Noun","A1"),
("time","waktu","/taim/","No time","Tidak ada waktu","Noun","A1"),
("day","hari","/dei/","Nice day","Hari bagus","Noun","A1"),
("night","malam","/nait/","Late night","Malam larut","Noun","A1"),
("morning","pagi","/mr.ni/","Morning vibe","Suasana pagi","Noun","A1"),
("today","hari ini","/t.dei/","Today ok","Hari ini oke","Adv","A1"),
("tomorrow","besok","/tmr.o/","See tomorrow","Ketemu besok","Adv","A1"),
("yesterday","kemarin","/is.t.dei/","Did yesterday","Dilakukan kemarin","Adv","A1"),
("see","lihat","/si/","See me","Lihat aku","Verb","A1"),
("hear","dengar","/hir/","Hear that","Dengar itu","Verb","A1"),
("love","cinta","/lv/","Love you","Cinta kamu","Verb","A1"),
("like","suka","/laik/","Like tea","Suka teh","Verb","A1"),
("want","ingin","/wnt/","Want this","Mau ini","Verb","A1"),
("need","butuh","/nid/","Need help","Butuh bantuan","Verb","A1")]
+ [("go","pergi","/go/","Go now","Pergi sekarang","Verb","A1"),
("come","datang","/km/","Come here","Kemari","Verb","A1"),
("play","main","/plei/","Play game","Main game","Verb","A1"),
("work","kerja","/wrk/","Hard work","Kerja keras","Verb","A1"),
("buy","beli","/bai/","Buy food","Beli makanan","Verb","A1"),
("sell","jual","/sel/","Sell car","Jual mobil","Verb","A1"),
("red","merah","/red/","Red rose","Mawar merah","Adj","A1"),
("blue","biru","/blu/","Blue sky","Langit biru","Adj","A1"),
("green","hijau","/grin/","Green grass","Rumput hijau","Adj","A1"),
("hand","tangan","/hand/","Wash hand","Cuci tangan","Noun","A1"),
("eye","mata","/ai/","Beautiful eye","Mata indah","Noun","A1"),
("head","kepala","/hed/","Head pain","Sakit kepala","Noun","A1"),
("foot","kaki","/ft/","Foot ball","Bola kaki","Noun","A1"),
("name","nama","/neim/","My name","Namaku","Noun","A1"),
("man","pria","/man/","Good man","Pria baik","Noun","A1"),
("woman","wanita","/wuman/","Strong woman","Wanita kuat","Noun","A1"),
("boy","cowok","/boi/","Smart boy","Cowok pintar","Noun","A1"),
("girl","cewek","/grl/","Nice girl","Cewek baik","Noun","A1"),
("door","pintu","/dr/","Close door","Tutup pintu","Noun","A1"),
("table","meja","/teibl/","On table","Di meja","Noun","A1")]
+ [("chair","kursi","/chr/","Sit chair","Duduk kursi","Noun","A1"),
("open","buka","/opn/","Open door","Buka pintu","Verb","A1"),
("close","tutup","/klos/","Close eyes","Tutup mata","Verb","A1"),
("help","bantu","/help/","Help me","Bantu aku","Verb","A1"),
("speak","bicara","/spik/","Speak loud","Bicara keras","Verb","A1"),
("listen","dengar","/lisn/","Listen Carefully","Dengarkan baik-baik","Verb","A1"),
("sun","matahari","/sn/","Sun shine","Sinar matahari","Noun","A1"),
("moon","bulan","/mun/","Full moon","Bulan purnama","Noun","A1"),
("star","bintang","/star/","Bright star","Bintang terang","Noun","A1"),
("tree","pohon","/tri/","Tall tree","Pohon tinggi","Noun","A1"),
("flower","bunga","/flaur/","Beautiful flower","Bunga cantik","Noun","A1"),
("rain","hujan","/rein/","Heavy rain","Hujan deras","Noun","A1"),
("wind","angin","/wind/","Strong wind","Angin kencang","Noun","A1"),
("fast","cepat","/fast/","Very fast","Sangat cepat","Adj","A1"),
("slow","lambat","/slo/","Slow down","Pelankan","Adj","A1"),
("easy","mudah","/izi/","Easy test","Tes mudah","Adj","A1"),
("hard","sulit","/hrd/","Hard life","Hidup sulit","Adj","A1"),
("clean","bersih","/klin/","Clean room","Kamar bersih","Adj","A1"),
("dirty","kotor","/dr.ti/","Dirty shirt","Baju kotor","Adj","A1"),
("travel","bepergian","/traevl/","Travel far","Bepergian jauh","Verb","A2")]
+ [("learn","belajar","/lrn/","Learn fast","Belajar cepat","Verb","A2"),
("teach","mengajar","/tich/","Teach kids","Mengajar anak","Verb","A2"),
("understand","paham","/andrstnd/","Understand me","Pahami aku","Verb","A2"),
("forget","lupa","/frget/","Forget it","Lupakan saja","Verb","A2"),
("begin","mulai","/bign/","Begin now","Mulai sekarang","Verb","A2"),
("finish","selesai","/finis/","Finish work","Selesaikan kerja","Verb","A2"),
("choose","pilih","/chuz/","Choose one","Pilih satu","Verb","A2"),
("borrow","pinjam","/borow/","Borrow money","Pinjam uang","Verb","A2"),
("bring","bawa","/brng/","Bring bag","Bawa tas","Verb","A2"),
("dream","mimpi","/drim/","Big dream","Mimpi besar","Noun","A2"),
("future","masa depan","/fucher/","Future job","Kerja masa depan","Noun","A2"),
("important","penting","/importnt/","Important news","Berita penting","Adj","A2"),
("famous","terkenal","/feimos/","Famous singer","Penyanyi terkenal","Adj","A2"),
("delicious","enak","/dilishas/","Delicious food","Makanan enak","Adj","A2"),
("boring","membosankan","/bor.ing/","Boring movie","Film membosankan","Adj","A2"),
("expensive","mahal","/kspensiv/","Expensive car","Mobil mahal","Adj","A2"),
("cheap","murah","/chip/","Cheap shoes","Sepatu murah","Adj","A2"),
("hospital","rumah sakit","/hospital/","Go hospital","Ke rumah sakit","Noun","A2"),
("money","uang","/mani/","Save money","Menabung","Noun","A2"),
("weather","cuaca","/wedr/","Good weather","Cuaca bagus","Noun","A2")]
def seed():
 import sqlite3
 db=sqlite3.connect('vocab.db')
 c=db.cursor()
 c.execute('CREATE TABLE IF NOT EXISTS vocabulary (id INTEGER PRIMARY KEY, word TEXT, meaning TEXT, pron TEXT, example TEXT, ex_m TEXT, pos TEXT, level TEXT)')
 c.execute('SELECT COUNT(*) FROM vocabulary')
 if c.fetchone()[0]==0:
  c.executemany('INSERT INTO vocabulary (word,meaning,pron,example,ex_m,pos,level) VALUES (?,?,?,?,?,?,?)',D)
  db.commit()
 db.close()
