"""
Database seed: 200 kosakata bahasa Inggris.
Dipanggil saat pertama kali bot dijalankan.
"""
from database import get_db

VOCABULARY_LIST = [
    # ===== A1 LEVEL (80 kata) =====
    ("apple", "apel", "/ˈæpəl/", "I eat an apple every day.",
     "Saya makan apel setiap hari.", "Noun", "A1", "food"),
    ("book", "buku", "/bʊk/", "This book is very interesting.",
     "Buku ini sangat menarik.", "Noun", "A1", "education"),
    ("water", "air", "/ˈwɔːtər/", "Please give me a glass of water.",
     "Tolong beri saya segelas air.", "Noun", "A1", "food"),
    ("eat", "makan", "/iːt/", "We eat breakfast at 7 AM.",
     "Kami makan sarapan jam 7 pagi.", "Verb", "A1", "daily"),
    ("drink", "minum", "/drɪŋk/", "I drink coffee in the morning.",
     "Saya minum kopi di pagi hari.", "Verb", "A1", "daily"),
    ("read", "membaca", "/riːd/", "She likes to read novels.",
     "Dia suka membaca novel.", "Verb", "A1", "education"),
    ("write", "menulis", "/raɪt/", "He writes a letter to his friend.",
     "Dia menulis surat untuk temannya.", "Verb", "A1", "education"),
    ("run", "berlari", "/rʌn/", "The boy runs very fast.",
     "Anak laki-laki itu berlari sangat cepat.", "Verb", "A1", "action"),
    ("walk", "berjalan", "/wɔːk/", "I walk to school every day.",
     "Saya berjalan ke sekolah setiap hari.", "Verb", "A1", "action"),
    ("happy", "bahagia", "/ˈhæpi/", "She is very happy today.",
     "Dia sangat bahagia hari ini.", "Adjective", "A1", "feeling"),
    ("sad", "sedih", "/sæd/", "Don't be sad, everything will be okay.",
     "Jangan sedih, semua akan baik-baik saja.", "Adjective", "A1", "feeling"),
    ("big", "besar", "/bɪɡ/", "They live in a big house.",
     "Mereka tinggal di rumah besar.", "Adjective", "A1", "size"),
    ("small", "kecil", "/smɔːl/", "I have a small cat.",
     "Saya punya kucing kecil.", "Adjective", "A1", "size"),
    ("good", "baik", "/ɡʊd/", "This is a good book to read.",
     "Ini adalah buku yang bagus untuk dibaca.", "Adjective", "A1", "quality"),
    ("bad", "buruk", "/bæd/", "The weather is bad today.",
     "Cuacanya buruk hari ini.", "Adjective", "A1", "quality"),
    ("new", "baru", "/njuː/", "I bought a new phone yesterday.",
     "Saya membeli ponsel baru kemarin.", "Adjective", "A1", "quality"),
    ("old", "tua", "/oʊld/", "My grandfather is very old.",
     "Kakek saya sudah sangat tua.", "Adjective", "A1", "quality"),
    ("hot", "panas", "/hɒt/", "The tea is too hot to drink.",
     "Tehnya terlalu panas untuk diminum.", "Adjective", "A1", "feeling"),
    ("cold", "dingin", "/koʊld/", "I like cold weather.",
     "Saya suka cuaca dingin.", "Adjective", "A1", "feeling"),
    ("family", "keluarga", "/ˈfæməli/", "Family is the most important thing.",
     "Keluarga adalah hal terpenting.", "Noun", "A1", "people"),
    ("friend", "teman", "/frend/", "She is my best friend.",
     "Dia adalah sahabat saya.", "Noun", "A1", "people"),
    ("house", "rumah", "/haʊs/", "Their house is near the park.",
     "Rumah mereka dekat dengan taman.", "Noun", "A1", "place"),
    ("school", "sekolah", "/skuːl/", "My school is very big.",
     "Sekolah saya sangat besar.", "Noun", "A1", "education"),
    ("car", "mobil", "/kɑːr/", "His car is red and fast.",
     "Mobilnya berwarna merah dan cepat.", "Noun", "A1", "vehicle"),
    ("dog", "anjing", "/dɒɡ/", "The dog is playing in the garden.",
     "Anjing itu sedang bermain di taman.", "Noun", "A1", "animal"),
    ("cat", "kucing", "/kæt/", "My cat loves to sleep.",
     "Kucing saya suka tidur.", "Noun", "A1", "animal"),
    ("food", "makanan", "/fuːd/", "The food at this restaurant is delicious.",
     "Makanan di restoran ini lezat.", "Noun", "A1", "food"),
    ("time", "waktu", "/taɪm/", "What time is it now?",
     "Jam berapa sekarang?", "Noun", "A1", "abstract"),
    ("day", "hari", "/deɪ/", "Have a nice day!",
     "Semoga harimu menyenangkan!", "Noun", "A1", "time"),
    ("night", "malam", "/naɪt/", "Good night, sleep well.",
     "Selamat malam, tidur yang nyenyak.", "Noun", "A1", "time"),
    ("morning", "pagi", "/ˈmɔːrnɪŋ/", "Good morning, everyone!",
     "Selamat pagi semuanya!", "Noun", "A1", "time"),
    ("afternoon", "siang", "/ˌæftərˈnuːn/", "I study in the afternoon.",
     "Saya belajar di siang hari.", "Noun", "A1", "time"),
    ("evening", "sore", "/ˈiːvnɪŋ/", "We meet every evening.",
     "Kami bertemu setiap sore.", "Noun", "A1", "time"),
    ("today", "hari ini", "/təˈdeɪ/", "Today is my birthday.",
     "Hari ini adalah ulang tahun saya.", "Adverb", "A1", "time"),
    ("tomorrow", "besok", "/təˈmɒrər/", "I will go to Jakarta tomorrow.",
     "Saya akan pergi ke Jakarta besok.", "Adverb", "A1", "time"),
    ("yesterday", "kemarin", "/ˈjestərdeɪ/", "It rained yesterday.",
     "Kemarin hujan.", "Adverb", "A1", "time"),
    ("see", "melihat", "/siː/", "I can see the mountain from here.",
     "Saya bisa melihat gunung dari sini.", "Verb", "A1", "action"),
    ("hear", "mendengar", "/hɪər/", "Can you hear me clearly?",
     "Bisakah kamu mendengarkanku dengan jelas?", "Verb", "A1", "action"),
    ("love", "mencintai", "/lʌv/", "I love my family so much.",
     "Saya sangat mencintai keluarga saya.", "Verb", "A1", "feeling"),
    ("like", "suka", "/laɪk/", "I like playing guitar.",
     "Saya suka bermain gitar.", "Verb", "A1", "feeling"),
    ("want", "ingin", "/wɒnt/", "I want to learn English.",
     "Saya ingin belajar bahasa Inggris.", "Verb", "A1", "feeling"),
    ("need", "butuh", "/niːd/", "We need more time to finish.",
     "Kami butuh lebih banyak waktu untuk selesai.", "Verb", "A1", "feeling"),
    ("go", "pergi", "/ɡəʊ/", "I go to work by bus.",
     "Saya pergi kerja dengan bus.", "Verb", "A1", "action"),
    ("come", "datang", "/kʌm/", "Please come to my party.",
     "Tolong datang ke pestaku.", "Verb", "A1", "action"),
    ("play", "bermain", "/pleɪ/", "Children love to play outside.",
     "Anak-anak suka bermain di luar.", "Verb", "A1", "action"),
    ("work", "bekerja", "/wɜːrk/", "She works at a hospital.",
     "Dia bekerja di rumah sakit.", "Verb", "A1", "action"),
    ("buy", "membeli", "/baɪ/", "I buy groceries every weekend.",
     "Saya membeli bahan makanan setiap akhir pekan.", "Verb", "A1", "action"),
    ("sell", "menjual", "/sel/", "They sell fresh fruits here.",
     "Mereka menjual buah segar di sini.", "Verb", "A1", "action"),
    ("red", "merah", "/red/", "Her dress is beautiful red.",
     "Gaunnya berwarna merah yang indah.", "Adjective", "A1", "color"),
    ("blue", "biru", "/bluː/", "The sky is blue today.",
     "Langitnya biru hari ini.", "Adjective", "A1", "color"),
    ("green", "hijau", "/ɡriːn/", "The leaves are green and fresh.",
     "Daun-daunnya berwarna hijau dan segar.", "Adjective", "A1", "color"),
    ("hand", "tangan", "/hænd/", "Wash your hands before eating.",
     "Cuci tanganmu sebelum makan.", "Noun", "A1", "body"),
    ("eye", "mata", "/aɪ/", "Her eyes are beautiful.",
     "Matanya indah.", "Noun", "A1", "body"),
    ("head", "kepala", "/hed/", "My head hurts a little.",
     "Kepala saya sedikit sakit.", "Noun", "A1", "body"),
    ("foot", "kaki", "/fʊt/", "My foot hurts after running.",
     "Kakiku sakit setelah berlari.", "Noun", "A1", "body"),
    ("hello", "halo", "/həˈləʊ/", "Hello, how are you today?",
     "Halo, apa kabarmu hari ini?", "Noun", "A1", "greeting"),
    ("name", "nama", "/neɪm/", "My name is Andi.",
     "Nama saya Andi.", "Noun", "A1", "identity"),
    ("man", "pria", "/mæn/", "That man is my teacher.",
     "Pria itu adalah guru saya.", "Noun", "A1", "people"),
    ("woman", "wanita", "/ˈwʊmən/", "The woman in blue is my mother.",
     "Wanita berbaju biru adalah ibu saya.", "Noun", "A1", "people"),
    ("boy", "anak laki-laki", "/bɔɪ/", "The boy is playing football.",
     "Anak laki-laki itu sedang bermain sepak bola.", "Noun", "A1", "people"),
    ("girl", "anak perempuan", "/ɡɜːrl/", "The girl reads a story book.",
     "Anak perempuan itu membaca buku cerita.", "Noun", "A1", "people"),
    ("door", "pintu", "/dɔːr/", "Please close the door.",
     "Tolong tutup pintunya.", "Noun", "A1", "place"),
    ("table", "meja", "/ˈteɪbəl/", "Put the book on the table.",
     "Letakkan buku di atas meja.", "Noun", "A1", "place"),
    ("chair", "kursi", "/tʃeər/", "Sit on the chair, please.",
     "Duduk di kursinya, tolong.", "Noun", "A1", "place"),
    ("open", "membuka", "/ˈəʊpən/", "Please open the window.",
     "Tolong buka jendelanya.", "Verb", "A1", "action"),
    ("close", "menutup", "/kləʊz/", "Close the door behind you.",
     "Tutup pintu di belakangmu.", "Verb", "A1", "action"),
    ("help", "membantu", "/help/", "Can you help me with this?",
     "Bisakah kamu membantuku dengan ini?", "Verb", "A1", "action"),
    ("speak", "berbicara", "/spiːk/", "Do you speak English?",
     "Apakah kamu bisa berbicara bahasa Inggris?", "Verb", "A1", "action"),
    ("listen", "mendengarkan", "/ˈlɪsən/", "Listen to the teacher carefully.",
     "Dengarkan guru dengan teliti.", "Verb", "A1", "action"),
    ("beauty", "kecantikan", "/ˈbjuːti/", "The beauty of nature amazes me.",
     "Keindahan alam membuatku takjub.", "Noun", "A1", "abstract"),
    ("sun", "matahari", "/sʌn/", "The sun shines brightly today.",
     "Matahari bersinar terang hari ini.", "Noun", "A1", "nature"),
    ("moon", "bulan", "/muːn/", "The moon looks so beautiful tonight.",
     "Bulan terlihat sangat indah malam ini.", "Noun", "A1", "nature"),
    ("star", "bintang", "/stɑːr/", "There are many stars in the sky.",
     "Ada banyak bintang di langit.", "Noun", "A1", "nature"),
    ("tree", "pohon", "/triː/", "The tree is very tall and old.",
     "Pohon itu sangat tinggi dan tua.", "Noun", "A1", "nature"),
    ("flower", "bunga", "/ˈflaʊər/", "She received beautiful flowers.",
     "Dia menerima bunga-bunga yang indah.", "Noun", "A1", "nature"),
    ("rain", "hujan", "/reɪn/", "The rain stopped an hour ago.",
     "Hujan berhenti satu jam yang lalu.", "Noun", "A1", "nature"),
    ("wind", "angin", "/wɪnd/", "The wind is very strong today.",
     "Anginnya sangat kencang hari ini.", "Noun", "A1", "nature"),
    ("fast", "cepat", "/fɑːst/", "He is a fast runner.",
     "Dia adalah pelari yang cepat.", "Adjective", "A1", "quality"),
    ("slow", "lambat", "/sləʊ/", "The internet is very slow today.",
     "Internetnya sangat lambat hari ini.", "Adjective", "A1", "quality"),
    ("easy", "mudah", "/ˈiːzi/", "This question is easy to answer.",
     "Pertanyaan ini mudah dijawab.", "Adjective", "A1", "quality"),
    ("hard", "sulit", "/hɑːrd/", "This problem is very hard to solve.",
     "Masalah ini sangat sulit diselesaikan.", "Adjective", "A1", "quality"),
    ("clean", "bersih", "/kliːn/", "Please keep the room clean.",
     "Tolong jaga ruangan tetap bersih.", "Adjective", "A1", "quality"),
    ("dirty", "kotor", "/ˈdɜːrti/", "Your hands are dirty, wash them.",
     "Tanganmu kotor, cuci mereka.", "Adjective", "A1", "quality"),

    # ===== A2 LEVEL (70 kata) =====
    ("travel", "bepergian", "/ˈtrævəl/", "I love to travel to new places.",
     "Saya suka bepergian ke tempat-tempat baru.", "Verb", "A2", "action"),
    ("learn", "belajar", "/lɜːrn/", "We learn English every day.",
     "Kami belajar bahasa Inggris setiap hari.", "Verb", "A2", "education"),
    ("teach", "mengajar", "/tiːtʃ/", "She teaches math at high school.",
     "Dia mengajar matematika di SMA.", "Verb", "A2", "education"),
    ("understand", "memahami", "/ˌʌndərˈstænd/",
     "I understand the lesson perfectly.",
     "Saya memahami pelajaran dengan sempurna.", "Verb", "A2", "thinking"),
    ("remember", "mengingat", "/rɪˈmembər/",
     "Do you remember my name?",
     "Apakah kamu ingat namaku?", "Verb", "A2", "thinking"),
    ("forget", "lupa", "/fərˈɡet/", "Don't forget to bring your umbrella.",
     "Jangan lupa bawa payungmu.", "Verb", "A2", "thinking"),
    ("answer", "menjawab", "/ˈænsər/", "Please answer the question honestly.",
     "Tolong jawab pertanyaannya dengan jujur.", "Verb", "A2", "communication"),
    ("question", "pertanyaan", "/ˈkwestʃən/",
     "That is a very good question.",
     "Itu pertanyaan yang sangat bagus.", "Noun", "A2", "communication"),
    ("begin", "memulai", "/bɪˈɡɪn/", "The class begins at 8 AM.",
     "Kelas dimulai jam 8 pagi.", "Verb", "A2", "action"),
    ("finish", "menyelesaikan", "/ˈfɪnɪʃ/",
     "I finish my homework before dinner.",
     "Saya menyelesaikan PR sebelum makan malam.", "Verb", "A2", "action"),
    ("choose", "memilih", "/tʃuːz/", "Choose the correct answer.",
     "Pilih jawaban yang benar.", "Verb", "A2", "action"),
    ("decide", "memutuskan", "/dɪˈsaɪd/", "We decided to go on vacation.",
     "Kami memutuskan untuk pergi liburan.", "Verb", "A2", "thinking"),
    ("borrow", "meminjam", "/ˈbɒrəʊ/", "Can I borrow your pen?",
     "Bisakah saya meminjam penamu?", "Verb", "A2", "action"),
    ("lend", "meminjamkan", "/lend/", "I can lend you some money.",
     "Saya bisa meminjamimu uang.", "Verb", "A2", "action"),
    ("bring", "membawa", "/brɪŋ/", "Don't forget to bring your book.",
     "Jangan lupa bawa bukumu.", "Verb", "A2", "action"),
    ("dream", "mimpi", "/driːm/", "I had a strange dream last night.",
     "Saya bermimpi aneh semalam.", "Noun", "A2", "abstract"),
    ("future", "masa depan", "/ˈfjuːtʃər/",
     "Think about your future career.",
     "Pikirkan karir masa depanmu.", "Noun", "A2", "abstract"),
    ("past", "masa lalu", "/pɑːst/", "Let the past stay in the past.",
     "Biarkan masa lalu tetap di masa lalu.", "Noun", "A2", "time"),
    ("present", "hadiah", "/ˈprezənt/", "I got a birthday present.",
     "Saya mendapat hadiah ulang tahun.", "Noun", "A2", "object"),
    ("important", "penting", "/ɪmˈpɔːrtənt/",
     "Health is more important than money.",
     "Kesehatan lebih penting dari uang.", "Adjective", "A2", "quality"),
    ("famous", "terkenal", "/ˈfeɪməs/", "He is a famous singer.",
     "Dia adalah penyanyi yang terkenal.", "Adjective", "A2", "quality"),
    ("delicious", "lezat", "/dɪˈlɪʃəs/", "This cake is very delicious.",
     "Kue ini sangat lezat.", "Adjective", "A2", "food"),
    ("boring", "membosankan", "/ˈbɔːrɪŋ/",
     "The movie was really boring.",
     "Filmnya sangat membosankan.", "Adjective", "A2", "feeling"),
    ("interesting", "menarik", "/ˈɪntrəstɪŋ/",
     "This book is very interesting.",
     "Buku ini sangat menarik.", "Adjective", "A2", "quality"),
    ("expensive", "mahal", "/ɪkˈspensɪv/",
     "That car is too expensive for me.",
     "Mobil itu terlalu mahal untukku.", "Adjective", "A2", "money"),
    ("cheap", "murah", "/tʃiːp/", "This shirt is very cheap.",
     "Kemeja ini sangat murah.", "Adjective", "A2", "money"),
    ("comfortable", "nyaman", "/ˈkʌmftəbəl/",
     "This sofa is very comfortable.",
     "Sofa ini sangat nyaman.", "Adjective", "A2", "feeling"),
    ("uncomfortable", "tidak nyaman", "/ʌnˈkʌmftəbəl/",
     "This chair is uncomfortable.",
     "Kursi ini tidak nyaman.", "Adjective", "A2", "feeling"),
    ("quickly", "dengan cepat", "/ˈkwɪkli/",
     "She finished her work quickly.",
     "Dia menyelesaikan pekerjaannya dengan cepat.", "Adverb", "A2", "manner"),
    ("slowly", "dengan lambat", "/ˈsləʊli/",
     "The old man walked slowly.",
     "Orang tua itu berjalan dengan lambat.", "Adverb", "A2", "manner"),
    ("loudly", "dengan keras", "/ˈlaʊdli/",
     "He spoke loudly so everyone could hear.",
     "Dia berbicara dengan keras agar semua bisa mendengar.",
     "Adverb", "A2", "manner"),
    ("quietly", "dengan diam", "/ˈkwaɪətli/",
     "The children sat quietly in the classroom.",
     "Anak-anak duduk diam di kelas.", "Adverb", "A2", "manner"),
    ("carefully", "dengan hati-hati", "/ˈkeəfəli/",
     "Please drive carefully on the highway.",
     "Tolong berkendara dengan hati-hati di jalan raya.",
     "Adverb", "A2", "manner"),
    ("easily", "dengan mudah", "/ˈiːzəli/",
     "He solved the puzzle easily.",
     "Dia menyelesaikan teka-teki itu dengan mudah.",
     "Adverb", "A2", "manner"),
    ("holiday", "liburan", "/ˈhɒlədeɪ/",
     "We are planning a holiday to Bali.",
     "Kami merencanakan liburan ke Bali.", "Noun", "A2", "time"),
    ("weekend", "akhir pekan", "/ˌwiːkˈend/",
     "What are your plans for the weekend?",
     "Apa rencanamu untuk akhir pekan?", "Noun", "A2", "time"),
    ("airport", "bandara", "/ˈeərpɔːrt/",
     "We arrived at the airport early.",
     "Kami tiba di bandara lebih awal.", "Noun", "A2", "place"),
    ("station", "stasiun", "/ˈsteɪʃən/",
     "I'll meet you at the train station.",
     "Saya akan menemuimu di stasiun kereta.", "Noun", "A2", "place"),
    ("ticket", "tiket", "/ˈtɪkɪt/", "I bought two tickets for the concert.",
     "Saya membeli dua tiket untuk konser.", "Noun", "A2", "object"),
    ("message", "pesan", "/ˈmesɪdʒ/",
     "I sent you a message yesterday.",
     "Saya mengirimimu pesan kemarin.", "Noun", "A2", "communication"),
    ("email", "surel", "/ˈiːmeɪl/",
     "Please check your email regularly.",
     "Tolong cek emailmu secara rutin.", "Noun", "A2", "communication"),
    ("phone", "telepon", "/fəʊn/", "My phone battery is running low.",
     "Baterai ponselku hampir habis.", "Noun", "A2", "technology"),
    ("computer", "komputer", "/kəmˈpjuːtər/",
     "I use my computer for work.",
     "Saya menggunakan komputer untuk bekerja.", "Noun", "A2", "technology"),
    ("internet", "internet", "/ˈɪntərnɛt/",
     "The internet connection is slow today.",
     "Koneksi internet lambat hari ini.", "Noun", "A2", "technology"),
    ("recipe", "resep", "/ˈresəpi/",
     "This is my grandmother's secret recipe.",
     "Ini adalah resep rahasia nenek.", "Noun", "A2", "food"),
    ("healthy", "sehat", "/ˈhelθi/",
     "Eating vegetables keeps you healthy.",
     "Makan sayuran menjagamu tetap sehat.", "Adjective", "A2", "health"),
    ("sick", "sakit", "/sɪk/", "I feel sick, I need to rest.",
     "Saya merasa sakit, perlu istirahat.", "Adjective", "A2", "health"),
    ("medicine", "obat", "/ˈmedsən/",
     "Take this medicine after meals.",
     "Minum obat ini setelah makan.", "Noun", "A2", "health"),
    ("doctor", "dokter", "/ˈdɒktər/",
     "The doctor will see you now.",
     "Dokter akan menemuimu sekarang.", "Noun", "A2", "people"),
    ("hospital", "rumah sakit", "/ˈhɒspɪtəl/",
     "The hospital is near the city center.",
     "Rumah sakit ada di dekat pusat kota.", "Noun", "A2", "place"),
    ("money", "uang", "/ˈmʌni/", "I need to save more money.",
     "Saya perlu menabung lebih banyak.", "Noun", "A2", "money"),
    ("price", "harga", "/praɪs/", "The price of gas is increasing.",
     "Harga bensin sedang naik.", "Noun", "A2", "money"),
    ("pay", "membayar", "/peɪ/", "I will pay for the dinner.",
     "Saya akan membayar makan malamnya.", "Verb", "A2", "money"),
    ("save", "menyimpan/menabung", "/seɪv/",
     "I save money for my education.",
     "Saya menabung untuk pendidikanku.", "Verb", "A2", "money"),
    ("enjoy", "menikmati", "/ɪnˈdʒɔɪ/",
     "I enjoy listening to music.",
     "Saya menikmati mendengarkan musik.", "Verb", "A2", "feeling"),
    ("prefer", "lebih suka", "/prɪˈfɜːr/",
     "I prefer tea over coffee.",
     "Saya lebih suka teh daripada kopi.", "Verb", "A2", "feeling"),
    ("agree", "setuju", "/əˈɡriː/", "I agree with your opinion.",
     "Saya setuju dengan pendapatmu.", "Verb", "A2", "thinking"),
    ("disagree", "tidak setuju", "/ˌdɪsəˈɡriː/",
     "I disagree with that statement.",
     "Saya tidak setuju dengan pernyataan itu.", "Verb", "A2", "thinking"),
    ("believe", "percaya", "/bɪˈliːv/", "I believe you can do it.",
     "Saya percaya kamu bisa melakukannya.", "Verb", "A2", "thinking"),
    ("hope", "berharap", "/həʊp/", "I hope you have a great day.",
     "Saya berharap harimu menyenangkan.", "Verb", "A2", "feeling"),
    ("wish", "berharap/menginginkan", "/wɪʃ/",
     "I wish you all the best.",
     "Saya mendoakan yang terbaik untukmu.", "Verb"
